# @package _global_
dataset_name: cingulate_UkBioBank_full
pickle_normal: datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rskeleton.pkl
numpy_all: datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rskeleton.npy
subjects_all: datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rskeleton_subject.csv
crop_dir: datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rcrops
foldlabel_dir: datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rlabels
foldlabel_all: datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rlabel.npy
subjects_foldlabel_all: datasets/UkBioBank/crops/2mm/CINGULATE/mask/Rlabel_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: UkBioBank/subjects_full.csv
nb_subjects: -1
subject_labels_file: UkBioBank/participants.csv
subject_column_name: 'Subject'
label_names: ["Gender"]
n_max: 1080