# @package _global_
model: SimCLR_supervised
with_labels: True
input_size: (1, 18, 40, 38)
temperature_initial: 0.1
temperature: 0.1
temperature_supervised: 0.1
sigma_labels: 0.2
sigma: 5
proportion_pure_contrastive: 1.0
drop_rate: 0.05
depth_decoder: 3
