# @package _global_
model: SimCLR_supervised
with_labels: True
input_size: (1, 18, 40, 38)
temperature_initial: 0.5
temperature: 0.5
sigma_labels: 0.1
sigma: 5
proportion_pure_contrastive: 0.
depth_decoder: 3