# @package _global_
batch_size: 16
pin_mem: True
partition: [0.8, 0.2]
lr: 4e-4
weight_decay: 5e-5
max_epochs: 251
nb_epochs_per_saving: 1
nb_epochs_per_tSNE: -1
nb_steps_per_flush_logs: 1
log_every_n_steps: 2
early_stopping_patience: 100
seed: 1
start_epoch: 0
checkpoint_path:
analysis_path: 
verbose: 1
checking: False