defaults:
  - hydra: no_save
  - hydra/job_logging: disabled
  - hydra/hydra_logging: disabled
  - dataset: cingulate_ACCpatterns_0
  - model: SimCLR_supervised
  - mode: encoder
  - augmentations: foldlabel
  - backbone: DenseNet
  - platform: cuda_brainvisa
  - trainer: default
  - classifier: svm
  - embeddings: embeddings