# @package _global_
# Characterization of the ConvNet model used
backbone_name: convnet
encoder_depth: 3
num_representation_features: 30
projection_head_hidden_layers:
batchnorm: False
projection_head_type: linear