# @package _global_
# Characterization of the DenseNet model used
backbone_name: pointnet
num_representation_features: 30 
num_outputs: 30 # not used, set equal to num_outputs
projection_head_hidden_layers:
projection_head_type: linear